<a href="https://colab.research.google.com/github/Timothy-John-Kaharian/CSST101-Activities/blob/main/CSST_101_Course_Enrollment_Sep_07_2026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **1. Create the Student Database**

In [94]:
students <- data.frame(
    Student_ID = c("S001", "S002", "S003", "S004", "S005", "S006", "S007", "S008"),
    Programming_Grade = c(88, 72, 91, 78, 65, 85, 74, 82),
    Math_Grade = c(85, 70, 88, 80, 68, 90, 73, 79),
    Attendance = c(92, 80, 95, 88, 70, 91, 76, 85),
    Prerequisite = c("Yes", "No", "Yes", "Yes", "No", "Yes", "No", "Yes")
)

students

cat("\n\n")
print(students)

  Student_ID Programming_Grade Math_Grade Attendance Prerequisite
1 S001       88                85         92         Yes
2 S002       72                70         80         No
3 S003       91                88         95         Yes
4 S004       78                80         88         Yes
5 S005       65                68         70         No
6 S006       85                90         91         Yes
7 S007       74                73         76         No
8 S008       82                79         85         Yes

  Student_ID Programming_Grade Math_Grade Attendance Prerequisite
1       S001                88         85         92          Yes
2       S002                72         70         80           No
3       S003                91         88         95          Yes
4       S004                78         80         88          Yes
5       S005                65         68         70           No
6       S006                85         90         91          Yes
7       S007                74         73         76           No
8       S008                82         79         85          Yes

## **2. Explore the Data**

In [95]:
summary(students)

cat("\n\n")

cat(paste0("Row: ", nrow(students), "\n"))
cat(paste0("Column: ", ncol(students), "\n"))
cat(paste0("Highest Grade: ", max(students$Programming_Grade), "\n"))
cat(paste0("Highest Attendance: ", max(students$Attendance), "\n"))
cat(paste0("Highest Math Grade: ", max(students$Math_Grade), "\n"))

     Student_ID Programming_Grade   Math_Grade      Attendance
 Length   :8    Min.   :65.00     Min.   :68.00   Min.   :70.00
 N.unique :8    1st Qu.:73.50     1st Qu.:72.25   1st Qu.:79.00
 N.blank  :0    Median :80.00     Median :79.50   Median :86.50
 Min.nchar:4    Mean   :79.38     Mean   :79.12   Mean   :84.62
 Max.nchar:4    3rd Qu.:85.75     3rd Qu.:85.75   3rd Qu.:91.25
                Max.   :91.00     Max.   :90.00   Max.   :95.00
    Prerequisite
 Length   :8
 N.unique :2
 N.blank  :0
 Min.nchar:2
 Max.nchar:3

Row: 8
Column: 5
Highest Grade: 91
Highest Attendance: 95
Highest Math Grade: 90

## **3. Enter a Student ID**

In [96]:
student_id <- readline("Enter Student ID: ")

print(student_id)

Enter Student ID: S001
[1] "S001"

## **4. Search the Data Frame**

In [97]:
student <- students[
  students$Student_ID == student_id,
]

student

  Student_ID Programming_Grade Math_Grade Attendance Prerequisite
1 S001       88                85         92         Yes

## **5. Check if the Student Exist**

In [98]:
  if (nrow(student) > 0) {
    cat("Student Found \n")
    student
  } else {
    cat("student not found \n")
    student
  }

Student Found

  Student_ID Programming_Grade Math_Grade Attendance Prerequisite
1 S001       88                85         92         Yes

## **6. Extract Student Information**

In [99]:
stud_id <- student$Student_ID
stud_grade <- student$Programming_Grade
stud_attendance <- student$Attendance
stud_mathGrade <- student$Math_Grade
stud_prere <- student$Prerequisite


cat(paste0("Student ID: ", stud_id, "\n"))
cat(paste0("Programming Grade: ", stud_grade, "\n"))
cat(paste0("Math Grade: ", stud_mathGrade, "\n"))
cat(paste0("Attendance Grade: ", stud_attendance, "\n"))
cat(paste0("Prerequisite: ", stud_prere, "\n"))

Student ID: S001
Programming Grade: 88
Math Grade: 85
Attendance Grade: 92
Prerequisite: Yes

## **7. Implement Rules**

In [100]:
student_eligibility <- function(programming, math, attendance, prerequisite)
if (programming >= 80 &&
    math >= 75 && attendance >= 80 &&
    prerequisite == "Yes"){
  print("Eligible")

}else if (programming >= 75 &&
          math >= 70 &&
          attendance >= 75){
  print("Conditionally Eligible")

}else{
 print("Not Eligible")
}

student_eligibility(78,87,54,"No")

students

[1] "Not Eligible"

  Student_ID Programming_Grade Math_Grade Attendance Prerequisite
1 S001       88                85         92         Yes
2 S002       72                70         80         No
3 S003       91                88         95         Yes
4 S004       78                80         88         Yes
5 S005       65                68         70         No
6 S006       85                90         91         Yes
7 S007       74                73         76         No
8 S008       82                79         85         Yes

## **8. Apply function to All Student**

In [101]:
students$Eligibility <- mapply(
  student_eligibility,
  students$Programming_Grade,
  students$Math_Grade,
  students$Attendance,
  students$Prerequisite
)

students

[1] "Eligible"
[1] "Not Eligible"
[1] "Eligible"
[1] "Conditionally Eligible"
[1] "Not Eligible"
[1] "Eligible"
[1] "Not Eligible"
[1] "Eligible"

  Student_ID Programming_Grade Math_Grade Attendance Prerequisite
1 S001       88                85         92         Yes
2 S002       72                70         80         No
3 S003       91                88         95         Yes
4 S004       78                80         88         Yes
5 S005       65                68         70         No
6 S006       85                90         91         Yes
7 S007       74                73         76         No
8 S008       82                79         85         Yes
  Eligibility
1 Eligible
2 Not Eligible
3 Eligible
4 Conditionally Eligible
5 Not Eligible
6 Eligible
7 Not Eligible
8 Eligible

## **9. Create Recommendation Rule**

In [102]:
get_recommendation <- function(eligibility) {

  if (eligibility == "Eligible") {
    return("Student may Enroll")

  } else if (eligibility == "Conditionally Eligible") {
    return("Consult Academic Adviser")

  } else {
    return("Complete requirements before enrollment")
  }
}

students$Recommendation <- sapply(
  students$Eligibility,
  get_recommendation
)

students

  Student_ID Programming_Grade Math_Grade Attendance Prerequisite
1 S001       88                85         92         Yes
2 S002       72                70         80         No
3 S003       91                88         95         Yes
4 S004       78                80         88         Yes
5 S005       65                68         70         No
6 S006       85                90         91         Yes
7 S007       74                73         76         No
8 S008       82                79         85         Yes
  Eligibility            Recommendation
1 Eligible               Student may Enroll
2 Not Eligible           Complete requirements before enrollment
3 Eligible               Student may Enroll
4 Conditionally Eligible Consult Academic Adviser
5 Not Eligible           Complete requirements before enrollment
6 Eligible               Student may Enroll
7 Not Eligible           Complete requirements before enrollment
8 Eligible               Student may Enroll

## **10. Expected Output**

In [103]:
student_id <- readline(prompt = "Enter Student ID: ")

student <- students[students$Student_ID == student_id, ]

if (nrow(student) > 0) {

  cat("\n========================================\n")
  cat("       COURSE ENROLLMENT ADVISER\n")
  cat("========================================\n\n")

  cat("Student ID:", student$Student_ID, "\n\n")

  cat(sprintf("Programming Grade: %.2f%%\n", student$Programming_Grade))
  cat(sprintf("Math Grade: %.2f%%\n", student$Math_Grade))
  cat(sprintf("Attendance: %.2f%%\n", student$Attendance))
  cat("Prerequisite:", student$Prerequisite, "\n\n")

  cat("Enrollment Status:\n")
  cat(student$Eligibility, "\n\n")

  cat("Recommendation:\n")
  cat(student$Recommendation, "\n")

  cat("========================================\n")

} else {
  cat("\nStudent ID not found.\n")
}

Enter Student ID: S004

========================================
       COURSE ENROLLMENT ADVISER
========================================

Student ID: S004

Programming Grade: 78.00%
Math Grade: 80.00%
Attendance: 88.00%
Prerequisite: Yes

Enrollment Status:
Conditionally Eligible

Recommendation:
Consult Academic Adviser
========================================